### ISSUE TITLE
Issue with Iex state struct cache key

### ISSUE THREAD

**Issue by AJReade** [nhpip/history#4]
Super cool project man I commented on your Reddit post and tried to get it up and running, but came across this compilation error. Let me know what you think.

![Screenshot 2021-09-09 at 00 30 51](https://user-images.githubusercontent.com/74275743/132599271-0fea3455-1a7f-4415-8b12-d03dc5ebc478.png)
![Screenshot 2021-09-09 at 00 31 34](https://user-images.githubusercontent.com/74275743/132599273-f8b9a14c-10a4-4a37-8f33-3947d7eb93f2.png)

**Comment by nhpip** [comment]
Hi,

Can you change cache to buffer and test for “” ?

Seems like they recently changed it.

**Comment by AJReade** [comment]
I changed the cache atom for buffer and it fixed the issue. What did you mean by 'test for "" '? Also, I'm now finding this warning for the string_to_token func.

![Screenshot 2021-09-09 at 01 47 47](https://user-images.githubusercontent.com/74275743/132604195-80ec4823-e191-41e1-ba4b-e544e14a015e.png)
![Screenshot 2021-09-09 at 01 48 21](https://user-images.githubusercontent.com/74275743/132604242-eaac8de7-835e-4c0f-bd67-64f0afe3258b.png)

**Comment by nhpip** [comment]
Yeah I need to try this on a newer version. 

Add another 1 next to the existing 1:

string_to_tokens(command, 1, 1, “”, [])

**Comment by nhpip** [comment]
Ok, so it should work now.

I’m tracking down a bug where the first command isn’t saved, but you should
be good to go. Just do a git pull and recompile.

**Comment by AJReade** [comment]
Yh it does thanks :).  I'll close this issue.
![Screenshot 2021-09-09 at 15 37 20](https://user-images.githubusercontent.com/74275743/132708740-c6ee0f6c-c238-4e28-b733-268b66019bd2.png)

**Comment by nhpip** [comment]
Thanks, I hope you find it useful
